<?php

$LAND = array(   "AD" => "Andorra",
                 "AE" => "Vereinigte Arabische Emirate",
                 "AF" => "Afghanistan",
                 "AG" => "Antigua und Barbuda",
                 "AI" => "Anguilla",
                 "AL" => "Albanien",
                 "AM" => "Armenien",
                 "AN" => "Niederländische Antillen",
                 "AO" => "Angola",
                 "AQ" => "Antarktis",
                 "AR" => "Argentinien",
                 "AS" => "Amerikanisch-Samoa",
                 "AT" => "Österreich",
                 "AU" => "Australien",
                 "AW" => "Aruba",
                 "AZ" => "Azerbaijan",
                 "BA" => "Bosnien-Herzegovina",
                 "BB" => "Barbados",
                 "BD" => "Bangladesh",
                 "BE" => "Belgien",
                 "BF" => "Burkina Faso",
                 "BG" => "Bulgarien",
                 "BH" => "Bahrain",
                 "BI" => "Burundi",
                 "BJ" => "Benin",
                 "BM" => "Bermuda",
                 "BN" => "Brunei Darussalam",
                 "BO" => "Bolivien",
                 "BR" => "Brasilien",
                 "BS" => "Bahamas",
                 "BT" => "Bhutan",
                 "BV" => "Bouvet Island",
                 "BW" => "Botswana",
                 "BY" => "Weißrußland (Belarus)",
                 "BZ" => "Belize",
                 "CA" => "Kanada",
                 "CC" => "Cocos (Keeling) Islands",
                 "CD" => "Demokratische Republik Kongo",
                 "CF" => "Zentralafrikanische Republik",
                 "CG" => "Kongo",
                 "CH" => "Schweiz",
                 "CI" => "Elfenbeinküste (Cote D'Ivoire)",
                 "CK" => "Cook Inseln",
                 "CL" => "Chile",
                 "CM" => "Kamerun",
                 "CN" => "China",
                 "CO" => "Kolumbien",
                 "CR" => "Costa Rica",
                 "CS" => "Tschechoslowakei (ehemalige)",
                 "CU" => "Kuba",
                 "CV" => "Kap Verde",
                 "CX" => "Christmas Island",
                 "CY" => "Zypern",
                 "CZ" => "Tschechische Republik",
                 "DE" => "Deutschland",
                 "DJ" => "Djibouti",
                 "DK" => "Dänemark",
                 "DM" => "Dominica",
                 "DO" => "Dominikanische Republik",
                 "DZ" => "Algerien",
                 "EC" => "Ecuador",
                 "EE" => "Estland",
                 "EG" => "Ägypten",
                 "EH" => "Westsahara",
                 "ER" => "Eritrea",
                 "ES" => "Spanien",
                 "ET" => "Äthiopien",
                 "FI" => "Finnland",
                 "FJ" => "Fiji",
                 "FK" => "Falkland-Inseln (Malvinas)",
                 "FM" => "Micronesien",
                 "FO" => "Faröer-Inseln",
                 "FR" => "Frankreich",
                 "FX" => "Frankreich",
                 "GA" => "Gabon",
                 "GD" => "Grenada",
                 "GE" => "Georgien",
                 "GF" => "Französisch Guyana",
                 "GG" => "Guernsey",
                 "GH" => "Ghana",
                 "GI" => "Gibraltar",
                 "GL" => "Grönland",
                 "GM" => "Gambia",
                 "GN" => "Guinea",
                 "GP" => "Guadeloupe",
                 "GQ" => "Äquatorialguinea",
                 "GR" => "Griechenland",
                 "GS" => "Südgeorgien und Südliche Sandwich-Inseln",
                 "GT" => "Guatemala",
                 "GU" => "Guam",
                 "GW" => "Guinea-Bissau",
                 "GY" => "Guyana",
                 "HK" => "Hong Kong",
                 "HM" => "Heard und Mc Donald Islands",
                 "HN" => "Honduras",
                 "HR" => "Kroatien",
                 "HT" => "Haiti",
                 "HU" => "Ungarn",
                 "ID" => "Indonesien",
                 "IE" => "Irland",
                 "IL" => "Israel",
                 "IN" => "Indien",
                 "IO" => "British Indian Ocean Territory",
                 "IQ" => "Irak",
                 "IR" => "Iran (Islamische Republik)",
                 "IS" => "Island",
                 "IT" => "Italien",
                 "JE" => "Jersey (Kanalinsel)",
                 "JM" => "Jamaica",
                 "JO" => "Jordanien",
                 "JP" => "Japan",
                 "KE" => "Kenya",
                 "KG" => "Kirgisien",
                 "KH" => "Königreich Kambodscha",
                 "KI" => "Kiribati",
                 "KM" => "Komoren",
                 "KN" => "Saint Kitts und Nevis",
                 "KP" => "Korea, Volksrepublik",
                 "KR" => "Süd Korea",
                 "KW" => "Kuwait",
                 "KY" => "Kayman Islands",
                 "KZ" => "Kasachstan",
                 "LA" => "Laos",
                 "LB" => "Libanon",
                 "LC" => "Saint Lucia",
                 "LI" => "Liechtenstein",
                 "LK" => "Sri Lanka",
                 "LR" => "Liberia",
                 "LS" => "Lesotho",
                 "LT" => "Litauen",
                 "LU" => "Luxemburg",
                 "LV" => "Lettland",
                 "LY" => "Libyen",
                 "MA" => "Marokko",
                 "MC" => "Monaco",
                 "MD" => "Moldawien",
                 "MG" => "Madagaskar",
                 "MH" => "Marshall-Inseln",
                 "MK" => "Mazedonien, ehem. Jugoslawische Republik",
                 "ML" => "Mali",
                 "MM" => "Myanmar",
                 "MN" => "Mongolei",
                 "MO" => "Macao",
                 "MP" => "Nördliche Marianneninseln",
                 "MQ" => "Martinique",
                 "MR" => "Mauretanien",
                 "MS" => "Montserrat",
                 "MT" => "Malta",
                 "MU" => "Mauritius",
                 "MV" => "Malediven",
                 "MW" => "Malawi",
                 "MX" => "Mexiko",
                 "MY" => "Malaysia",
                 "MZ" => "Mozambique",
                 "NA" => "Namibia",
                 "NC" => "Neukaledonien",
                 "NE" => "Niger",
                 "NF" => "Norfolk Island",
                 "NG" => "Nigeria",
                 "NI" => "Nicaragua",
                 "NL" => "Niederlande",
                 "NO" => "Norwegen",
                 "NP" => "Nepal",
                 "NR" => "Nauru",
                 "NU" => "Niue",
                 "NZ" => "Neuseeland",
                 "OM" => "Oman",
                 "PA" => "Panama",
                 "PE" => "Peru",
                 "PF" => "Französisch Polynesien",
                 "PG" => "Papua Neuguinea",
                 "PH" => "Philippinen",
                 "PK" => "Pakistan",
                 "PL" => "Polen",
                 "PM" => "St. Pierre und Miquelon",
                 "PN" => "Pitcairn",
                 "PR" => "Puerto Rico",
                 "PT" => "Portugal",
                 "PW" => "Palau",
                 "PY" => "Paraguay",
                 "QA" => "Katar",
                 "RE" => "Réunion",
                 "RO" => "Rumänien",
                 "RU" => "Russische Föderation",
                 "RW" => "Ruanda",
                 "SA" => "Saudi Arabien",
                 "SB" => "Salomonen",
                 "SC" => "Seychellen",
                 "SD" => "Sudan",
                 "SE" => "Schweden",
                 "SG" => "Singapur",
                 "SH" => "St. Helena",
                 "SI" => "Slowenien",
                 "SJ" => "Svalbard und Jan Mayen Islands",
                 "SK" => "Slowakei",
                 "SL" => "Sierra Leone",
                 "SM" => "San Marino",
                 "SN" => "Senegal",
                 "SO" => "Somalia",
                 "SR" => "Surinam",
                 "ST" => "Sao Tome und Principe",
                 "SV" => "El Salvador",
                 "SY" => "Syrien, Arabische Republik",
                 "SZ" => "Swaziland",
                 "TC" => "Turk und Caicos-Inseln",
                 "TD" => "Tschad",
                 "TF" => "Französisches Südl.Territorium",
                 "TG" => "Togo",
                 "TH" => "Thailand",
                 "TJ" => "Tadschikistan",
                 "TK" => "Tokelau",
                 "TM" => "Turkmenistan",
                 "TN" => "Tunesien",
                 "TO" => "Tonga",
                 "TP" => "Ost-Timor",
                 "TR" => "Türkei",
                 "TT" => "Trinidad und Tobago",
                 "TV" => "Tuvalu",
                 "TW" => "Republik China (Taiwan)",
                 "TZ" => "Tansania, United Republic of",
                 "UA" => "Ukraine",
                 "UG" => "Uganda",
                 "GB" => "United Kingdom",
                 "UK" => "United Kingdom",
                 "US" => "USA",
                 "UM" => "Vereinigte Staaten, Minor Outlying Islands",
                 "UY" => "Uruguay",
                 "UZ" => "Usbekistan",
                 "VA" => "Vatikanstaat",
                 "VC" => "Saint Vincent und Grenadines",
                 "VE" => "Venezuela",
                 "VG" => "Virgin Islands (Britisch)",
                 "VI" => "Virgin Islands (U.S.)",
                 "VN" => "Vietnam",
                 "VU" => "Vanuatu",
                 "WF" => "Wallis und Futuna Islands",
                 "WS" => "Samoa",
                 "XK" => "Kosovo, Republik",
                 "YE" => "Jemen",
                 "YT" => "Mayotte",
                 "YU" => "Jugoslawien",
                 "ZA" => "Südafrika",
                 "ZM" => "Sambia",
                 "ZW" => "Zimbabwe"
              );
                 
$EULAENDER = array(	"INLAND" => 1,	// Inland, Array-ID für Taxzones
					"EU_OHNE" => 2,	// EU ohne USt-ID Nummer, Array-ID für Taxzones
					"EU_MIT" => 3,	// EU mit USt-ID Nummer, Array-ID für Taxzones
					"WORLD" => 4,	// Außerhalb EU, Array-ID für Taxzones
					"TAXRATE" => 5,	// Standardsteuersatz fuer Inland und EU ohne USt-ID Nummer, Array-ID für Taxzones
	
					"AT",
					"BE",
					"BG",
					"CY",
					"CZ",
					"DE",
					"DK",
					"EE",
					"GR",
					"ES",
					"FI",
					"FR",
					"FX",
					"HR",
					"HU",
					"IE",
					"IT",
					"LT",
					"LU",
					"LV",
					"MC",
					"MT",
					"NL",
					"PL",
					"PT",
					"RO",
					"SE",
					"SI",
					"SK",
					"UK",
					"GB");
								
$VERSAND = array(	"AFN" => "Amazon",
					"MFN" => "Händler");


$paramsOrders = array(	"MarketplaceId" => "MarketplaceId",    
						"SalesChannel" => "SalesChannel",

						"OrderType" => "OrderType",
						"OrderStatus" => "OrderStatus",
						"SellerOrderId" => "SellerOrderId",
						"AmazonOrderId" => "AmazonOrderId",
						"purchase-order-number" => "",
						"FulfillmentChannel" => "FulfillmentChannel",
						"IsReplacementOrder" => "IsReplacementOrder",
						"IsBusinessOrder" => "IsBusinessOrder",
						"IsPremiumOrder" => "IsPremiumOrder",
						"IsPrime" => "IsPrime",

						"ShipmentServiceLevelCategory" => "ShipmentServiceLevelCategory",
						"ShipServiceLevel" => "ShipServiceLevel",

						"Amount" => "Amount",
						"CurrencyCode" => "CurrencyCode",
						"price-designation" => "",
						"PaymentMethod" => "PaymentMethod",
						"PaymentMethodDetail" => "PaymentMethodDetail",	// Invoice ist hier das Zeichen für verspätete Verbuchung
																		// PaymentMethodDetails -> kann enthalten/ enthält mehrere PaymentMethodDetail
						"payments-date" => "",			// Datum, an dem die Bezahlung verifiziert ist (bzw. an dem die Rechnung gestellt wird (nicht das Faelligkeits der Rechnung))

						"NumberOfItems" => "NumberOfItemsShipped",

						"PurchaseDate" => "PurchaseDate",
						"LastUpdateDate" => "LastUpdateDate",
						"LatestShipDate" => "LatestShipDate",
						"EarliestShipDate" => "EarliestShipDate",
						"shipment-date" => "",		// Datum, an dem die Ware verschickt wurde
						"reporting-date" => "",		// Datum, an dem die Infoemail von Amazon kommt
						"delivery-time-zone" => "",
						"delivery-Instructions" => "",

						"BuyerName" => "BuyerName",
						"Title" => "",
						"Name" => "",
						"AddressLine1" => "",
						"AddressLine2" => "",
						"AddressLine3" => "",
						"PostalCode" => "",
						"City" => "",
						"StateOrRegion" => "",
						"CountryCode" => "",
						"buyer-cst-number" => "",
						"buyer-vat-number" => "",

						"recipient-title" => "Title",
						"recipient-name" => "",
						"ship-address-1" => "",
						"ship-address-2" => "",
						"ship-address-3" => "",
						"ship-postal-code" => "",
						"ship-city" => "",
						"ship-state" => "",
						"ship-country" => "",
						"ship-phone-number" => "",
						
						"BuyerEmail" => "BuyerEmail",
						"Phone" => "Phone",
						"OrderComment" => "OrderComment",

						"carrier" => "",
						"tracking-number" => "",
						"estimated-arrival-date" => "",
						"fulfillment-center-id" => "",
						"fulfillment-channel" => "",

						"Language" => "SalesChannel",
						
						"ShippedByAmazonTFM" => "ShippedByAmazonTFM",
						"LatestDeliveryDate" => "LatestDeliveryDate",
						"EarliestDeliveryDate" => "EarliestDeliveryDate",
						
						"tax_number" => "",
						"tax_included" => ""
						);

$paramsOrderItems = array(	"OrderItemId" => "",
							"SellerSKU" => "",
							"ASIN" => "",
							"Title" => "",

							"shipment-id" => "",
							"shipment-item-id" => "",
							"merchant-order-item-id" => "",

							"ItemPrice" => "",
							"ItemTax" => "",
							"PromotionDiscount" => "",
							"ShippingPrice" => "",
							"ShippingTax" => "",
							"ShippingDiscount" => "",
							"GiftWrapPrice" => "",
							"GiftWrapTax" => "",

							"QuantityOrdered" => "",
							"QuantityShipped" => "",
							
							"SerialNumber" => ""
							);

$paramsOrdersReportFBA = array(	"MarketplaceId" => "",
								"SalesChannel" => "sales-channel",

								"OrderType" => "",
								"OrderStatus" => "",
								"SellerOrderId" => "merchant-order-id",
								"AmazonOrderId" => "amazon-order-id",
								"purchase-order-number" => "",
								"FulfillmentChannel" => "fulfillment-channel",
								"IsReplacementOrder" => "",
								"IsBusinessOrder" => "",
								"IsPremiumOrder" => "",
								"IsPrime" => "",

								"ShipmentServiceLevelCategory" => "",
								"ShipServiceLevel" => "ship-service-level",

								"Amount" => "",
								"CurrencyCode" => "currency",
								"price-designation" => "",
								"PaymentMethod" => "",
								"PaymentMethodDetail" => "",					// Invoice ist hier das Zeichen für verspätete Verbuchung
																				// PaymentMethodDetails -> kann enthalten/ enthält mehrere PaymentMethodDetail
								"payments-date" => "payments-date",				// Datum, an dem die Bezahlung verifiziert ist (bzw. an dem die Rechnung gestellt wird (nicht das Faelligkeits der Rechnung))

								"NumberOfItems" => "quantity-shipped",
								
								"PurchaseDate" => "purchase-date",
								"LastUpdateDate" => "",
								"LatestShipDate" => "",
								"EarliestShipDate" => "",
								"shipment-date" => "shipment-date",		// Datum, an dem die Ware verschickt wurde
								"reporting-date" => "reporting-date",	// Datum, an dem die Infoemail von Amazon kommt
								"delivery-time-zone" => "",
								"delivery-Instructions" => "",

								"BuyerName" => "",
								"Title" => "",
								"Name" => "buyer-name",
								"AddressLine1" =>"bill-address-1",
								"AddressLine2" => "bill-address-2",
								"AddressLine3" => "bill-address-3",
								"PostalCode" => "bill-postal-code",
								"City" => "bill-city",
								"StateOrRegion" => "bill-state",
								"CountryCode" => "bill-country",
								"buyer-cst-number" => "",
								"buyer-vat-number" => "",

								"recipient-title" => "",
								"recipient-name" => "recipient-name",
								"ship-address-1" => "ship-address-1",
								"ship-address-2" => "ship-address-2",
								"ship-address-3" => "ship-address-3",
								"ship-postal-code" => "ship-postal-code",
								"ship-city" => "ship-city",
								"ship-state" => "ship-state",
								"ship-country" => "ship-country",
								"ship-phone-number" => "ship-phone-number",

								"BuyerEmail" => "buyer-email",
								"Phone" => "buyer-phone-number",
								"OrderComment" => "",

								"carrier" => "carrier",
								"tracking-number" => "tracking-number",
								"estimated-arrival-date" => "estimated-arrival-date",
								"fulfillment-center-id" => "fulfillment-center-id",
								"fulfillment-channel" => "fulfillment-channel",

								"Language" => "sales-channel",
								
								"ShippedByAmazonTFM" => "",
								"LatestDeliveryDate" => "",
								"EarliestDeliveryDate" => "",
								
								"tax_number" => "",
								"tax_included" => ""
								);

$paramsOrderItemsReportFBA = array(	"OrderItemId" => "amazon-order-item-id",
									"SellerSKU" => "sku",
									"ASIN" => "",
									"Title" => "product-name",

									"shipment-id" => "shipment-id",
									"shipment-item-id" => "shipment-item-id",
									"merchant-order-item-id" => "merchant-order-item-id",

									"ItemPrice" => "item-price",
									"ItemTax" => "item-tax",
									"PromotionDiscount" => "item-promotion-discount",
									"ShippingPrice" => "shipping-price",
									"ShippingTax" => "shipping-tax",
									"ShippingDiscount" => "ship-promotion-discount",
									"GiftWrapPrice" => "gift-wrap-price",
									"GiftWrapTax" => "gift-wrap-tax",

									"QuantityOrdered" => "quantity-shipped",
									"QuantityShipped" => "quantity-shipped",
							
									"SerialNumber" => ""
									);

$paramsOrdersReportMFN = array(	"MarketplaceId" => "",
								"SalesChannel" => "sales-channel",
								
								"OrderType" => "",
								"OrderStatus" => "",
								"SellerOrderId" => "",
								"AmazonOrderId" => "order-id",
								"purchase-order-number" => "purchase-order-number",
								"FulfillmentChannel" => "",
								"IsReplacementOrder" => "",
								"IsBusinessOrder" => "is-business-order",
								"IsPremiumOrder" => "",
								"IsPrime" => "",

								"ShipmentServiceLevelCategory" => "ship-service-level",
								"ShipServiceLevel" => "ship-service-level",
								
								"Amount" => "",
								"CurrencyCode" => "currency",
								"price-designation" => "price-designation",
								"PaymentMethod" => "",
								"PaymentMethodDetail" => "",					// Invoice ist hier das Zeichen für verspätete Verbuchung
																				// PaymentMethodDetails -> kann enthalten/ enthält mehrere PaymentMethodDetail
								"payments-date" => "payments-date",				// Datum, an dem die Bezahlung verifiziert ist (bzw. an dem die Rechnung gestellt wird (nicht das Faelligkeits der Rechnung))

								"NumberOfItems" => "quantity-purchased",
								
								"PurchaseDate" => "purchase-date",
								"LastUpdateDate" => "",
								"LatestShipDate" => "delivery-end-date",
								"EarliestShipDate" => "delivery-start-date",
								"shipment-date" => "",		// Datum, an dem die Ware verschickt wurde
								"reporting-date" => "",		// Datum, an dem die Infoemail von Amazon kommt
								"delivery-time-zone" => "delivery-time-zone",
								"delivery-Instructions" => "delivery-Instructions",


								"BuyerName" => "",
								"Title" => "",
								"Name" => "buyer-name",
								"AddressLine1" => "bill-address-1",
								"AddressLine2" => "bill-address-2",
								"AddressLine3" => "bill-address-3",
								"PostalCode" => "bill-postal-code",
								"City" => "bill-city",
								"StateOrRegion" => "bill-state",
								"CountryCode" => "bill-country",
								"buyer-cst-number" => "buyer-cst-number",
								"buyer-vat-number" => "buyer-vat-number",
								
								"recipient-title" => "",
								"recipient-name" => "recipient-name",
								"ship-address-1" => "ship-address-1",
								"ship-address-2" => "ship-address-2",
								"ship-address-3" => "ship-address-3",
								"ship-postal-code" => "ship-postal-code",
								"ship-city" => "ship-city",
								"ship-state" => "ship-state",
								"ship-country" => "ship-country",
								"ship-phone-number" => "ship-phone-number",
								
								"BuyerEmail" => "buyer-email",
								"Phone" => "buyer-phone-number",
								"OrderComment" => "",

								"carrier" => "",
								"tracking-number" => "",
								"estimated-arrival-date" => "",
								"fulfillment-center-id" => "",
								"fulfillment-channel" => "",

								"Language" => "sales-channel",

								"ShippedByAmazonTFM" => "",
								"LatestDeliveryDate" => "",
								"EarliestDeliveryDate" => "",
								
								"tax_number" => "",
								"tax_included" => ""
								);

$paramsOrderItemsReportMFN = array(	"OrderItemId" => "order-item-id",
									"SellerSKU" => "sku",
									"ASIN" => "",
									"Title" => "product-name",

									"shipment-id" => "",
									"shipment-item-id" => "",
									"merchant-order-item-id" => "",

									"ItemPrice" => "item-price",
									"ItemTax" => "item-tax",
									"PromotionDiscount" => "",
									"ShippingPrice" => "shipping-price",
									"ShippingTax" => "shipping-tax",
									"ShippingDiscount" => "",
									"GiftWrapPrice" => "", "GiftWrapTax" => "",
									
									"QuantityOrdered" => "quantity-purchased",
									"QuantityShipped" => "",
																
									"SerialNumber" => ""
									);
?>